export interface SiteConfig {
  name: string;
  shortName: string;
  description: string;
  url: string;
  ogImage: string;
  logo: string;
  links: {
    twitter?: string;
    github?: string;
    linkedin?: string;
    youtube?: string;
  };
  twitterHandle: string;
  creator: string;
  email: string;
  phone: string;
  address: {
    streetAddress: string;
    city: string;
    region: string;
    postalCode: string;
    country: string;
  };
  foundingDate: string;
  priceRange: string;
  keywords: string[];
}

export const siteConfig: SiteConfig = {
  name: "DataVision AI",
  shortName: "DataVision",
  description: "AI-powered data visualization platform. Chat with your data, get instant visualizations, and discover insights in seconds.",
  url: "https://datavision-ai.vercel.app",
  ogImage: "https://datavision-ai.vercel.app/og-image.png",
  logo: "https://datavision-ai.vercel.app/icon.svg",
  links: {
    twitter: "https://twitter.com/datavisionai",
    linkedin: "https://linkedin.com/company/datavisionai",
    youtube: "https://youtube.com/@datavisionai"
  },
  twitterHandle: "@datavisionai",
  creator: "DataVision AI Team",
  email: "hello@datavision.ai",
  phone: "+1-415-555-0100",
  address: {
    streetAddress: "100 Market Street, Suite 400",
    city: "San Francisco",
    region: "CA",
    postalCode: "94105",
    country: "US"
  },
  foundingDate: "2024-01-01",
  priceRange: "Free–$$$",
  keywords: [
    // Primary — high-intent
    "AI data visualization",
    "data visualization software",
    "business intelligence platform",
    "data analytics platform",
    "AI analytics tool",
    // Conversational / NLP
    "chat with your data",
    "natural language data queries",
    "ask questions to your data",
    "conversational analytics",
    "AI-powered data insights",
    "talk to your database",
    "natural language SQL",
    // No-code / low-code
    "no-code analytics",
    "no-code dashboards",
    "SQL-free data analysis",
    "build dashboards without code",
    "no-code BI tool",
    "drag and drop dashboard builder",
    // Use cases
    "automated business insights",
    "real-time data visualization",
    "instant data visualization",
    "AI-powered dashboards",
    "interactive charts and graphs",
    "data exploration platform",
    "automated data analysis",
    "data storytelling tool",
    "self-service analytics",
    "embedded analytics",
    // Enterprise
    "enterprise analytics AI",
    "AI business intelligence",
    "enterprise data platform",
    "secure data analytics",
    "enterprise BI software",
    "large-scale data platform",
    "multi-source data analytics",
    // Comparisons / alternatives
    "Tableau alternative",
    "Power BI alternative",
    "Looker alternative",
    "Metabase alternative",
    "better than Tableau",
    "AI Tableau replacement",
    // Verticals
    "data analytics for startups",
    "data analytics for enterprises",
    "marketing analytics AI",
    "sales analytics dashboard",
    "finance analytics platform",
    "e-commerce data analytics",
    "SaaS analytics tool",
    // Long-tail
    "how to visualize data with AI",
    "best AI data visualization tool 2025",
    "data analysis without SQL",
    "smart dashboards",
    "data insights automation",
    "AI data platform",
    "turn CSV into dashboard",
    "connect database and visualize",
    "AI chart generator",
    "auto generate charts from data",
    "data dashboard in seconds",
    // Data visualization — types & formats
    "bar chart maker online",
    "line chart generator",
    "pie chart creator",
    "scatter plot tool",
    "heatmap visualization",
    "treemap chart tool",
    "funnel chart maker",
    "waterfall chart generator",
    "histogram maker online",
    "area chart tool",
    "bubble chart maker",
    "gantt chart software",
    "geographic data visualization",
    "geospatial data mapping",
    "data map visualization",
    "network graph visualization",
    "sankey diagram maker",
    "KPI dashboard builder",
    "metrics dashboard software",
    "executive dashboard tool",
    // Visual insights — discovery
    "visual data exploration",
    "visual analytics platform",
    "get insights from data visually",
    "data pattern recognition AI",
    "trend analysis visualization",
    "anomaly detection dashboard",
    "outlier detection in data",
    "data correlation tool",
    "visual data discovery",
    "exploratory data analysis tool",
    "EDA tool online",
    "data profiling tool",
    "automated insight generation",
    "AI data pattern detection",
    "predictive analytics visualization",
    "forecasting dashboard",
    "data trend forecasting",
    "cohort analysis tool",
    "retention analytics visualization",
    "funnel analysis dashboard",
    // Data analysis — workflows
    "data analysis tool online",
    "online data analyzer",
    "data report generator",
    "automated reporting tool",
    "business report automation",
    "data summary generator",
    "drag and drop data analysis",
    "point and click analytics",
    "spreadsheet to dashboard",
    "Excel to dashboard converter",
    "Google Sheets dashboard",
    "CSV data visualization",
    "JSON data visualization",
    "database visualization tool",
    "SQL query to chart",
    "query results visualization",
    "data aggregation tool",
    "cross-database analytics",
    "multi-dataset analysis",
    // AI & machine learning analytics
    "machine learning data visualization",
    "AI-driven analytics",
    "deep learning insights",
    "neural network visualization",
    "AI model performance dashboard",
    "ML pipeline visualization",
    "automated machine learning insights",
    "generative AI analytics",
    "LLM data analysis",
    "GPT data visualization",
    "AI insight extraction",
    "intelligent data analysis",
    "smart data visualization",
    "cognitive analytics platform",
    "AI report generation",
    "natural language report builder",
    "AI-powered trend analysis",
    "AI business insights tool",
    "AI data summarization",
    // Real-time & streaming data
    "real-time analytics dashboard",
    "live data visualization",
    "streaming data dashboard",
    "real-time KPI monitoring",
    "live business metrics",
    "real-time database charts",
    "real-time reporting tool",
    "event stream visualization",
    "IoT data visualization",
    "sensor data dashboard",
    "operational analytics dashboard",
    "monitoring dashboard software",
    "uptime analytics visualization",
    "server metrics dashboard",
    "application performance dashboard",
    // Cloud & infrastructure analytics
    "cloud analytics platform",
    "cloud data visualization",
    "AWS analytics dashboard",
    "Google BigQuery visualization",
    "Snowflake data visualization",
    "Databricks analytics tool",
    "Azure analytics visualization",
    "cloud BI tool",
    "data warehouse visualization",
    "data lake analytics",
    "cloud-native BI platform",
    "serverless analytics tool",
    // Industry verticals — extended
    "healthcare data analytics",
    "healthcare dashboard software",
    "clinical data visualization",
    "patient data analytics tool",
    "financial data visualization",
    "stock market data visualization",
    "investment analytics dashboard",
    "retail analytics platform",
    "supply chain analytics visualization",
    "logistics data dashboard",
    "HR analytics dashboard",
    "people analytics tool",
    "workforce data visualization",
    "education data analytics",
    "student performance dashboard",
    "nonprofit data analytics",
    "government data visualization",
    "real estate analytics dashboard",
    "operations analytics tool",
    "product analytics dashboard",
    // User roles & personas
    "analytics tool for data analysts",
    "dashboard tool for product managers",
    "BI tool for non-technical teams",
    "data visualization for executives",
    "reporting tool for marketing teams",
    "analytics for sales teams",
    "dashboard for business owners",
    "data tool for small business",
    "analytics for data-driven teams",
    "visualization tool for researchers",
    // Integrations & connectors
    "PostgreSQL dashboard tool",
    "MySQL visualization tool",
    "MongoDB analytics dashboard",
    "Salesforce analytics visualization",
    "HubSpot data dashboard",
    "Stripe analytics dashboard",
    "Shopify analytics visualization",
    "Airtable visualization tool",
    "Notion analytics integration",
    "Slack data insights",
    "Zapier analytics dashboard",
    "REST API data visualization",
    "GraphQL analytics tool",
    "webhook data dashboard",
    // Advanced analytics features
    "drill-down analytics",
    "slice and dice data",
    "pivot table alternative",
    "what-if analysis tool",
    "scenario planning dashboard",
    "multi-dimensional data analysis",
    "time series analysis tool",
    "seasonality analysis dashboard",
    "attribution analytics tool",
    "A/B test visualization",
    "experiment results dashboard",
    "customer journey analytics",
    "user behavior analytics",
    "clickstream analytics visualization",
    "conversion analytics dashboard",
    // Mobile & collaboration
    "mobile analytics dashboard",
    "tablet data visualization",
    "responsive dashboard builder",
    "shared analytics dashboard",
    "team analytics workspace",
    "collaborative data analysis",
    "dashboard sharing tool",
    "embedded dashboard software",
    "white label analytics platform",
    "analytics API for developers"
  ]
};
